### ISSUE TITLE
Logo For Box Library

### ISSUE THREAD

**Issue by photopic** [siranabontan/boxlibrary#1]
Hi i want to contribute on your project, i have design a logo for you, if you like it i will send pull request
![hori](https://user-images.githubusercontent.com/38512758/38964404-dff3c34a-43a0-11e8-96c4-52db7a460f2c.png)

**Comment by siranabontan** [comment]
I like it, are you a designer? and Is this free?

**Comment by photopic** [comment]
Yes, the logo is free under license GPLv4.. Okay i have send pull request, please accept it

**Comment by photopic** [comment]
And this is link editable files https://drive.google.com/open?id=1-zniXO7NL4xg23XV-VkF87a686HERp2Z

**Comment by siranabontan** [comment]
Merged. Thank u
